In [1]:
import numpy as np

In [2]:
lista =[1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
array =np.array(lista) #convierte un arreglo en un arreglo de numpy

In [8]:
type(array)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
matriz =[[1,2,3],[4,5,6],[7,8,9]]
matriz =np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#index
array[0] #1 dimensión

1

In [11]:
array[0] + array[5]

7

In [14]:
matriz #2 dimensiones

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
matriz[0]

array([1, 2, 3])

In [16]:
matriz[0,2]

3

In [17]:
#slices
array[1:6] #toma un segmento excluyendo el limite derecho

array([2, 3, 4, 5, 6])

In [19]:
array[:6] #desde el inicio

array([1, 2, 3, 4, 5, 6])

In [20]:
array[3:] #hasta el final

array([4, 5, 6, 7, 8, 9])

In [21]:
array[::] #todo el contenido

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
array[::3] #todo cada tercer elemento partiendo del primero

array([1, 4, 7])

In [26]:
array[-1] #primer valor del final al principio

9

In [27]:
array[-3:] #funcionan los slices con indices negativos

array([7, 8, 9])

In [28]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [30]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [39]:
#sandbox
matriz_3d = [
    [
        [1,2,3],[2,3,4],[3,4,5]
    ],
    [
        [4,5,6],[5,6,7],[6,7,8]
    ],
    [
        [7,8,9],[8,9,10],[9,10,11]   
    ]
]
matriz_3d =np.array(matriz_3d)
matriz_3d

array([[[ 1,  2,  3],
        [ 2,  3,  4],
        [ 3,  4,  5]],

       [[ 4,  5,  6],
        [ 5,  6,  7],
        [ 6,  7,  8]],

       [[ 7,  8,  9],
        [ 8,  9, 10],
        [ 9, 10, 11]]])

In [40]:
matriz_3d[1:]

array([[[ 4,  5,  6],
        [ 5,  6,  7],
        [ 6,  7,  8]],

       [[ 7,  8,  9],
        [ 8,  9, 10],
        [ 9, 10, 11]]])

In [42]:
matriz_3d[1:,-1:]

array([[[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [44]:
matriz_3d[1:,-1:,-1:]

array([[[ 8]],

       [[11]]])