In [6]:
import numpy as np

In [7]:
array =np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [8]:
array.dtype #tipo de datos del array

dtype('int64')

In [9]:
array_f =np.array([1,2,3,4], dtype='float64') #establecer el tipo del array
array_f.dtype

dtype('float64')

In [10]:
array =array.astype(np.float64) #refundir un array en flotante
array.dtype

dtype('float64')

In [11]:
array= array.astype(np.bool_)
array

array([ True,  True,  True,  True])

In [12]:
array =array.astype(np.string_)
array

array([b'True', b'True', b'True', b'True'], dtype='|S5')

In [13]:
array =np.array(['0','1','2','3'])
array

array(['0', '1', '2', '3'], dtype='<U1')

In [14]:
array = array.astype(np.int8)
array

array([0, 1, 2, 3], dtype=int8)

In [16]:
array = np.array(['dsa', '2', '4'])
#array = array.astype(np.int8) #error de refundición

In [ ]:
#los arrays de numpy solo pueden tener un solo tipo de datos