In [1]:
import numpy as np

Dimensiones
- Scalar dim =0 (un dato individual)
- Vector dim =0 (un arreglo o lista regular [sin vectores hijos])
- Matrix dim =2 (un arreglo de Vectores)
- Tensor dim =3
- Tensor dim =n ?


In [3]:
   scalar =np.array(42)
   scalar

array(42)

Dimensiones (.ndim)

In [5]:
scalar.ndim

0

In [6]:
vector = np.array([1,2,3])
vector.ndim

1

In [7]:
matriz = np.array([[1,2,3],[4,5,6]])
matriz.ndim

2

In [8]:
tensor3d =np.array([matriz, matriz])
tensor3d.ndim

3

In [9]:
tensor4d =np.array([tensor3d, tensor3d])
tensor4d.ndim

4

Agregar o eliminar dimensiones

In [24]:
vector10 = np.array([1,2,3], ndmin=10) #dimensiones del array
vector10.ndim

10

In [25]:
vector10

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

In [26]:
vector =np.array([1,2,3])
vector.ndim

1

In [27]:
vector_exp = np.expand_dims(vector, axis=0) #axis 0 = una dimension a nivel de filas, axis =1 columnas
vector_exp.ndim

2

In [30]:
vector10, vector10.ndim

(array([[[[[[[[[[1, 2, 3]]]]]]]]]]), 10)

In [33]:
vector_simp =np.squeeze(vector10) #elimina las dimensiones inutilizadas
vector_simp, vector_simp.ndim

(array([1, 2, 3]), 1)

In [39]:
#sandbox
tensor4d, tensor4d.ndim
tensor5d =np.array(np.array([tensor4d, tensor4d]))
tensor5d, tensor5d.ndim


(array([[[[[1, 2, 3],
           [4, 5, 6]],
 
          [[1, 2, 3],
           [4, 5, 6]]],
 
 
         [[[1, 2, 3],
           [4, 5, 6]],
 
          [[1, 2, 3],
           [4, 5, 6]]]],
 
 
 
        [[[[1, 2, 3],
           [4, 5, 6]],
 
          [[1, 2, 3],
           [4, 5, 6]]],
 
 
         [[[1, 2, 3],
           [4, 5, 6]],
 
          [[1, 2, 3],
           [4, 5, 6]]]]]), 5)

In [40]:
tensor5d_exp0 =np.expand_dims(tensor5d, axis=0)
tensor5d_exp0, tensor5d_exp0.ndim

(array([[[[[[1, 2, 3],
            [4, 5, 6]],
 
           [[1, 2, 3],
            [4, 5, 6]]],
 
 
          [[[1, 2, 3],
            [4, 5, 6]],
 
           [[1, 2, 3],
            [4, 5, 6]]]],
 
 
 
         [[[[1, 2, 3],
            [4, 5, 6]],
 
           [[1, 2, 3],
            [4, 5, 6]]],
 
 
          [[[1, 2, 3],
            [4, 5, 6]],
 
           [[1, 2, 3],
            [4, 5, 6]]]]]]), 6)

In [42]:
tensor5d_exp1 =np.expand_dims(tensor5d, axis=1)
tensor5d_exp1, tensor5d_exp1.ndim

(array([[[[[[1, 2, 3],
            [4, 5, 6]],
 
           [[1, 2, 3],
            [4, 5, 6]]],
 
 
          [[[1, 2, 3],
            [4, 5, 6]],
 
           [[1, 2, 3],
            [4, 5, 6]]]]],
 
 
 
 
        [[[[[1, 2, 3],
            [4, 5, 6]],
 
           [[1, 2, 3],
            [4, 5, 6]]],
 
 
          [[[1, 2, 3],
            [4, 5, 6]],
 
           [[1, 2, 3],
            [4, 5, 6]]]]]]), 6)