In [1]:
import numpy as np

In [3]:
list(range(0,10)) #crea una listaa de python en el rango indicado, excluye el último

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(0,10) #crea un arreglo de numpy con el rango suministrado

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2) #numeros de dos en dos en el rango suministrado (step)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3) #crea un arreglo de ceros con los elementos y dimensiones suministrados

array([0., 0., 0.])

In [11]:
np.zeros((10,10)) #dos dimensiones de 10x10 (por ejemplo una imágen en esta resolución)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((10,10)) #unos

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,10,100) #rango inicial, rango final, número de datos, crea un arreglo distribuido entre el rango

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [21]:
np.eye(10) #genera una matriz con uno en la diagonal y cero en el resto de espacios

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
np.random.rand() #valor pseudoaletorio

0.013607327832960037

In [24]:
np.random.rand(4) #vector de 4 columnas, con valores pseudoaleatorios

array([0.74317388, 0.14504279, 0.78431405, 0.74752634])

In [25]:
np.random.rand(4,4) #matriz de 4x4 con valores pseudoaletorios

array([[0.88957605, 0.41572792, 0.4713703 , 0.48014157],
       [0.34278918, 0.35680377, 0.36811683, 0.96892913],
       [0.82241596, 0.76816145, 0.93624064, 0.09185505],
       [0.55030231, 0.99519792, 0.09306347, 0.56451442]])

In [28]:
np.random.randint(1, 15) #valor aleatorio entre el rango de enteros

7

In [30]:
np.random.randint(1,100, (10,10)) #valores aleatorios dentro del rango de enteros, en una matriz de 10x10

array([[70, 73, 56, 57, 18, 66,  7, 29, 43, 45],
       [96, 58, 86, 61, 34,  1, 87, 65, 56, 88],
       [43,  1, 96, 77, 40, 70,  3, 23, 87, 94],
       [21, 24, 10, 83, 77, 24, 31, 23, 23, 27],
       [38, 85, 94, 23, 56, 77, 86, 52, 59, 71],
       [99, 17,  9, 56, 14, 89, 43, 73, 90, 57],
       [22, 80, 26, 83, 61,  5, 16, 18, 15, 11],
       [73, 30, 96,  1, 23, 51, 81, 53, 92,  8],
       [63, 45, 79, 22, 97, 53, 67, 75, 89, 78],
       [96, 81, 58, 49,  3, 61, 35, 68,  6, 44]])