In [1]:
import numpy as np

Shape   = forma del arreglo

In [4]:
rand_array_1_10 = np.random.randint(1,10, (3,2))
rand_array_1_10

array([[9, 3],
       [4, 9],
       [9, 5]])

In [17]:
rand_array_1_10.shape #retorna la forma del array, cuantas filas y columnas tengo

(3, 2)

In [16]:
rand_array_1_10.reshape(1,6) #cambiar la forma del array y ordenar en la nueva forma los valores contenidos

array([[9, 3, 4, 9, 9, 5]])

In [8]:
#rand_array_1_10.reshape(1,3) #error por la cantidad de valores (6), no coincide con 1x3

In [9]:
rand_array_1_10.reshape(3,2)

array([[9, 3],
       [4, 9],
       [9, 5]])

In [12]:
rand_array_1_10

array([[9, 3],
       [4, 9],
       [9, 5]])

In [14]:
np.reshape(rand_array_1_10, (1,6)) #sinónimo

array([[9, 3, 4, 9, 9, 5]])

In [19]:
rand_array_1_10

array([[9, 3],
       [4, 9],
       [9, 5]])

In [22]:
np.reshape(rand_array_1_10, (2,3), 'C') #ordenado como lo haría el lenguaje c

array([[9, 3, 4],
       [9, 9, 5]])

In [23]:
np.reshape(rand_array_1_10, (2,3), 'F') #ordenado como lo haría el lenguaje Fortran

array([[9, 9, 9],
       [4, 3, 5]])

In [24]:
np.reshape(rand_array_1_10, (2,3), 'A') #ordenado como esté mejor optimizado en mi sistema

array([[9, 3, 4],
       [9, 9, 5]])

In [27]:
#sandbox
tensor = np.random.randint(1,100, (4,5,6))
tensor, tensor.ndim

(array([[[84, 16, 50, 35, 59, 23],
         [13,  7,  9, 60,  8, 79],
         [ 5, 32, 26, 58,  1, 47],
         [26,  7, 52, 20, 14, 95],
         [23,  6, 55, 45, 28, 34]],
 
        [[74, 25, 83, 97, 92, 26],
         [34, 92, 68, 25, 83,  9],
         [11, 85, 20, 31, 66, 10],
         [11,  2, 44, 84, 54, 94],
         [30, 34, 44, 83, 72, 75]],
 
        [[20, 83, 56, 54,  3, 66],
         [84, 29, 79, 70, 74, 42],
         [22, 85, 54, 77, 92, 46],
         [30, 52, 69, 18, 20, 25],
         [91,  5,  8, 52, 88, 46]],
 
        [[27, 17, 28, 67, 65, 34],
         [86, 12, 18, 10, 19, 44],
         [69, 38, 66, 45, 34, 87],
         [51, 90,  2, 34, 75, 87],
         [85, 54, 20, 94, 64, 40]]]), 3)

In [30]:
np.reshape(tensor, (20, 3, 2))

array([[[84, 16],
        [50, 35],
        [59, 23]],

       [[13,  7],
        [ 9, 60],
        [ 8, 79]],

       [[ 5, 32],
        [26, 58],
        [ 1, 47]],

       [[26,  7],
        [52, 20],
        [14, 95]],

       [[23,  6],
        [55, 45],
        [28, 34]],

       [[74, 25],
        [83, 97],
        [92, 26]],

       [[34, 92],
        [68, 25],
        [83,  9]],

       [[11, 85],
        [20, 31],
        [66, 10]],

       [[11,  2],
        [44, 84],
        [54, 94]],

       [[30, 34],
        [44, 83],
        [72, 75]],

       [[20, 83],
        [56, 54],
        [ 3, 66]],

       [[84, 29],
        [79, 70],
        [74, 42]],

       [[22, 85],
        [54, 77],
        [92, 46]],

       [[30, 52],
        [69, 18],
        [20, 25]],

       [[91,  5],
        [ 8, 52],
        [88, 46]],

       [[27, 17],
        [28, 67],
        [65, 34]],

       [[86, 12],
        [18, 10],
        [19, 44]],

       [[69, 38],
        [66, 45],
        [34,