In [1]:
import numpy as np

In [14]:
vector =np.random.randint(1, 20, 10)
vector

array([ 8, 16,  5,  4, 11, 17, 12, 19, 12,  6])

In [15]:
matriz =vector.reshape(2,5)
matriz

array([[ 8, 16,  5,  4, 11],
       [17, 12, 19, 12,  6]])

In [18]:
vector.max() #número mas grande del vector

19

In [19]:
matriz.max() # || de la matriz

19

In [20]:
matriz.max(1) #mayor por el eje 1 (filas)

array([16, 19])

In [22]:
matriz.max(0) #mayor por el eje 0 (columnas)

array([17, 16, 19, 12, 11])

In [24]:
vector.argmax() #indice donde se encuentra el valor mas grande del vector (con preferencia del indice mas bajo)

7

In [27]:
matriz.argmax(0) # ||, en el eje 0 (columnas)

array([1, 0, 1, 1, 0])

- min y argmin son esencialmente lo contrario a max y argmax

In [28]:
vector.min()

4

In [29]:
matriz.min()

4

In [30]:
vector.argmin()

3

In [32]:
matriz.argmin(0)

array([0, 1, 0, 0, 1])

In [35]:
vector

array([ 8, 16,  5,  4, 11, 17, 12, 19, 12,  6])

In [36]:
vector.ptp() #diferencia entre el pico mas alto y el mas bajo

15

In [38]:
matriz

array([[ 8, 16,  5,  4, 11],
       [17, 12, 19, 12,  6]])

In [39]:
matriz.ptp()

15

In [40]:
matriz.ptp(0)

array([ 9,  4, 14,  8,  5])

In [44]:
vector

array([ 8, 16,  5,  4, 11, 17, 12, 19, 12,  6])

In [51]:
np.percentile(vector, 50) #valor que se encuentra en la mitad (la mediana)

11.5

In [49]:
np.percentile(vector, 0) #mas bajo

4.0

In [48]:
np.percentile(vector, 100) #mas alto

19.0

In [54]:
vector.sort() #ordena de menor a mayor los valores
vector

array([ 4,  5,  6,  8, 11, 12, 12, 16, 17, 19])

In [56]:
np.median(vector) #la mediana

11.5

In [58]:
np.median(matriz, 0) #mediana del eje cero

array([ 8. ,  8.5, 11. , 12.5, 15. ])

In [61]:
np.std(vector) #desviación estándar o típica

4.959838707054898

In [64]:
np.var(vector) #varianza

24.6

In [65]:
np.std(vector) **2 #la desviación estándar elevada al cuadrado es igual a la varianza

24.599999999999998

In [67]:
import math

In [69]:
math.sqrt(np.var(vector)) #la raíz cuadrada de la varianza es la desviación estándar

4.959838707054898

In [78]:
np.mean(vector) #media (promedio)

11.0

In [79]:
matriza =np.array([[1,2], [3,4]])
matrizb =np.array([5,6])

In [100]:
matriza, matrizb

(array([[1, 2],
        [3, 4]]), array([[5, 6]]))

In [80]:
#np.concatenate((matriza, matrizb), axis=0) #no cuentan con la misma cantidad de dimensiones por lo tanto no se pueden cocatenar

In [81]:
matriza.ndim, matrizb.ndim

(2, 1)

In [87]:
matrizb =np.expand_dims(matrizb, axis=0)

In [92]:
np.concatenate((matriza, matrizb), axis=0) #se concatenan las matrices en el eje cero (columnas)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
#np.concatenate((matriza, matrizb), axis=1) #si quisieramos contatenar en el eje 1 (filas) nos dá un error, por la disposición de los valores

In [95]:
#se podría manejar con un reshape

In [98]:
matrizb, matrizb.T #o con la transpuesta (cambia la matriz de 1x2 a 2x1)

(array([[5, 6]]), array([[5],
        [6]]))

In [99]:
np.concatenate((matriza, matrizb.T), axis=1) #se concatenan correctamente con el uso de la transpuesta

array([[1, 2, 5],
       [3, 4, 6]])