In [1]:
import numpy as np

In [3]:
vector =np.arange(0,20)
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
piece_of_vector =vector[0:11]
piece_of_vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
piece_of_vector[:] =0 ##establecer en 0 todos los valores del slice
piece_of_vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
vector #es afectado por el slice de referencia

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
piece_of_vector_copy =piece_of_vector.copy() #con este método creamos una copia de la refencia a memoria de la variable (deep copy)
piece_of_vector_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
piece_of_vector_copy[:] =100
piece_of_vector_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [13]:
vector

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11, 12, 13, 14, 15, 16,
       17, 18, 19])