In [2]:
import numpy as np

In [7]:
vector = np.linspace(1,10,10, dtype='int8')
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [9]:
response_conditions = vector >5 #condiciones explícitas
response_conditions

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [10]:
vector[response_conditions]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [11]:
vector[vector >5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [14]:
vector[(vector >5) & (vector <8)]

array([6, 7], dtype=int8)

In [16]:
vector[(vector >5) & (vector <8)] =0
vector

array([ 1,  2,  3,  4,  5,  0,  0,  8,  9, 10], dtype=int8)

In [18]:
vector[vector==0]

array([0, 0], dtype=int8)