<a href="https://colab.research.google.com/github/NeroAlfonso/curso_numpy_pandas/blob/main/9_operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
py_vector =list([1,2,3,4,5,6,7,8])
py_vector

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
py_vector *2 #multiplica los elementos del array en conjunto (duplica) en lugar de realizar la operación en cada elemento

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
vector =np.array(py_vector)
vector

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
vector *2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
vector /2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
vector **2

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [ ]:
vector2 = vector /2
vector2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
vector2 * vector

array([ 0.5,  2. ,  4.5,  8. , 12.5, 18. , 24.5, 32. ])

In [ ]:
vector / vector2

array([2., 2., 2., 2., 2., 2., 2., 2.])

In [ ]:
matriz =vector.reshape(2,4)
matriz2 =matriz.copy()
matriz, matriz2

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [ ]:
matriz - matriz2

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
matriz * matriz2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [ ]:
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
matriz2.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
np.matmul(matriz, matriz2.T) #multiplicación de producto punto

array([[ 30,  70],
       [ 70, 174]])

In [ ]:
matriz @ matriz2.T #sinónimo

array([[ 30,  70],
       [ 70, 174]])