In [28]:
import numpy as np

In [29]:
py_vector =list([1,2,3,4,5,6,7,8])
py_vector

[1, 2, 3, 4, 5, 6, 7, 8]

In [30]:
py_vector *2 #multiplica los elementos del array en conjunto (duplica) en lugar de realizar la operación en cada elemento

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [31]:
vector =np.array(py_vector)
vector

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
vector *2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [33]:
vector /2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [34]:
vector **2

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [35]:
vector2 = vector /2
vector2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [36]:
vector2 * vector

array([ 0.5,  2. ,  4.5,  8. , 12.5, 18. , 24.5, 32. ])

In [37]:
vector / vector2

array([2., 2., 2., 2., 2., 2., 2., 2.])

In [38]:
matriz =vector.reshape(2,4)
matriz2 =matriz.copy()
matriz, matriz2

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [39]:
matriz - matriz2

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [40]:
matriz * matriz2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [41]:
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
matriz2.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [42]:
np.matmul(matriz, matriz2.T) #multiplicación de producto punto

array([[ 30,  70],
       [ 70, 174]])

In [45]:
matriz @ matriz2.T #sinónimo

array([[ 30,  70],
       [ 70, 174]])